# This workflow performs test builds across a diversity of supported platforms
#
#     - ubuntu-latest  - gcc
#     - ubuntu-latest  - clang
#     - ubuntu-24.04   - gcc   (For backwards compatablity)
#     - windows-latest - cl
#     - macos-latest   - clang
